- hosts: all 
  vars:
    docker_add_repo: yes
    pip_install_packages:
      - name: docker==6.1.3
      - name: docker-compose

  roles:
    - robertdebock.fail2ban
    - firewall
    - cockpit
    - geerlingguy.pip
    - geerlingguy.docker
    - minecraft