- hosts: all 
  become: yes 
  vars_files:
    - ./vault.yml
  vars:
    ansible_become_pass: '{{ ansible_user_pass }}'
    docker_add_repo: yes
    pip_install_packages:
      - name: docker==6.1.3
      - name: docker-compose

  roles:
    - robertdebock.fail2ban
    - firewall
    - cockpit
    - geerlingguy.pip
    - geerlingguy.docker
    - kibana
    - minecraft
  
  tasks:
    - name: Disallow SSH password authentication
      lineinfile: 
        dest: /etc/ssh/sshd_config
        regexp: "^PasswordAuthentication"
        line: "PasswordAuthentication no"
        state: present
        validate: sshd -t -f %s
      notify:
        - restart sshd

