---
- name: create minecraft folder
  file:
    path: "{{ mc_docker_dir }}"
    group: docker
    state: directory 

- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: ../files/docker-compose.yml
    dest: "{{ mc_docker_dir }}/docker-compose.yml"

- name: Get infos on container
  community.docker.docker_container_info:
    name: minecraft_mc_1
  register: result

- name: Create and start the minecraft server 
  community.docker.docker_compose:
    project_src: "{{ mc_docker_dir }}" 
  register: output
  when: result.exists

- name: Verify that mc is running 
  ansible.builtin.assert:
    that:
      - "output.services.mc.minecraft_mc_1.state.running"

- name: install logrotate
  apt:
    name: logrotate
    state: present

# - name: configure logrotate for mc server 
#   ansible.builtin.blockinfile:
#     path: /etc/logrotate.d/minecraft_server
#     create: yes
#     block: |
#       compress
#       {{ mc_docker_dir }}/**/* {
#         rotate 5
#         dateext
#         dateformat _%Y-%m-%d
#         daily
#         extension .tar.gz
#         sharedscripts
#         copy
#         missingok

#         # postrotate
#           # rsync -e 'ssh -p23 ' -avzr {{mc_docker_dir}} {{hetzner_storage_box_username}}@{{hetzner_storage_box_host}}:/home
#         # endscript
#       }
