---
- name: create minecraft folder
  file:
    path: "{{ mc_docker_dir }}"
    group: docker
    state: directory 

- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: ../files/docker-compose.yml
    dest: "{{ mc_docker_dir }}/docker-compose.yml"
- name: Create and start services
  community.docker.docker_compose:
    project_src: "{{ mc_docker_dir }}" 
  register: output

# - name: Verify that mc is running 
#   ansible.builtin.assert:
#     that:
#       - "output.services.minecraft.state.running"

- name: install logrotate
  apt:
    name: logrotate
    state: present

## todo it so it doesnt leak the username
- name: configure logrotate 
  ansible.builtin.blockinfile:
    path: /etc/logrotate.d/minecraft_server
    create: yes
    block: |
      compress
      {{ mc_docker_dir }} {
        rotate 5
        dateext
        dateformat _%Y-%m-%d
        daily
        extension .tar.gz
        sharedscripts
        copy
        missingok

        postrotate
          rsync -avzr {{mc_docker_dir}} {{hetzner_storage_box_username}}@{{hetzner_storage_box_host}}:/home
        endscript
      }
