---
- name: Add k8 key 
  ansible.builtin.get_url:
    url: https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key
    dest: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    mode: '0644'
    force: true


- name: Add Example repo
  ansible.builtin.apt_repository:
    filename: k8-repo
    repo: 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /'
  
- name: install k8
  apt: 
    name:
      - kubelet 
      - kubeadm
      - kubectl