---
- name: install ufw
  apt:
    name: ufw
    state: latest 

- name: allow ssh
  community.general.ufw:
    rule: allow
    name: OpenSSH

- name: Allow port 25665(mc) 
  community.general.ufw:
    rule: allow
    port: 25665
    proto: tcp

- name: Allow port 9090(cockpit) 
  community.general.ufw:
    rule: allow
    port: 9090 
    proto: tcp

- name: enable ufw firewall
  community.general.ufw:
    state: enabled