---
- name: Start flask project with inline definition
  community.docker.docker_compose:
      project_name: wireguard 
      definition:
        version: '2'
        services:
          wireguard:
            image: ghcr.io/wg-easy/wg-easy
            environment:
              - LANG=de
              - WG_HOST={{ansible_all_ipv4_addresses}}
              # TODO PLEASE CHANGE ME I AM NOT SUPPOSED TO BE HERE 
              - PASSWORD=DBA4D753-E52C-40FF-90A8-9F26C8AAD862
              - WG_PORT=51820
              - PORT=51821 
            volumes:
              - /docker/wireguard:/etc/wireguard
            ports:
              - "51820:51820"
              - "51821:51821"
            cap_add:
              - NET_ADMIN
              - SYS_MODULE
            sysctls:
              - net.ipv4.ip_forward=1
              - net.ipv4.conf.all.src_valid_mark=1